# PrimeSeller-Fork Configuration

# Format: language_COUNTRY
# After changing this parameter, the server will load default material names
language: en_US

# Time settings
time-zone: "America/New_York"  # All time zones: https://timeie.com/
time-format: "hhh. mmm. sss."
datetime-format: "MM/dd/yyyy HH:mm"

inv-sell-priority: "LIMITED"

economy:
  # You can use CoinsEngine instead of Vault
  coins-engine:
    enable: false  # If disabled, Vault will be used.
    currency: "money"

understating-price:
  enable: true  # Enable price reduction on sales
  items: 512  # How many items must be sold to reduce the price
  percent: 0.1  # Percentage by which the price will be reduced on sale
  min-percent: 30  # Minimum percentage of the original price below which the price will not drop

# Auto-sell
autosell:
  check-interval: 100  # How often to check inventories for auto-selling (in ticks - 20 ticks = 1 second)
  enable-autosell-messages: false  # Enable messages about auto-selling items

prefix: "<gradient:#5637bc:#9258ff>[Buyer]</gradient> <#b9b9b9>|"

# Mini-Messages is not supported here
placeholders:
  autosell-enabled: "&aEnabled"
  autosell-disabled: "&cDisabled"
