# PrimeSeller-Fork Configuration
# Поддержка MiniMessage формата: https://docs.advntr.dev/minimessage/format.html

# формат: language_COUNTRY
# после изменения этого параметра сервер загрузит имена материалов по умолчанию
language: ru_RU

# Настройки времени
time-zone: "Europe/Moscow"  # все time-zone: https://timeie.com/
time-format: "hhч. mmм. ssс."
datetime-format: "dd.MM.yy HH:mm"

inv-sell-priority: "LIMITED"

economy:
  # Можно использовать CoinsEngine вместо Vault
  coins-engine:
    enable: false  # Если отключено, будет использоваться Vault.
    currency: "money"

# Включить снижение цены при продаже
# (percent = Процент, на который будет снижена цена при продаже)
understating-price:
  enable: true
  items: 512  # Сколько предметов надо продать для уменьшения цены
  percent: '0,1'  # Меньше 0,01 устанавливать не стоит, не будет работать (вместо этого увеличивайте items)
  min-percent: 30  # Минимальный процент от суммы, ниже которого цена не опустится

# Автопродажа
autosell:
  check-interval: 100  # Как часто нужно проверять инвентари для автопродажи (в тиках - 20 тиков = 1 секунда)
  enable-autosell-messages: false  # включение сообщений об авто-продаже продаже предметов

prefix: "<gradient:#5637bc:#9258ff>[Скупщик]</gradient> <#b9b9b9>|"
